### ISSUE TITLE
lean源码编译打包不能运行

### ISSUE THREAD

**Issue by tianiue** [sbwml/openwrt-alist#1]
安装ipk可以，开机会自动启动，用源码编译进去不能运行，出现这样日志

daemon.info procd: Instance alist::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by sbwml** [comment]
我没有用过lean源码，你只需要确认一点就是编译进去固件后，直接终端执行 ```alist``` 能不能正常启动

**Comment by tianiue** [comment]
我不能启动，这是我打包的固件，你看看原因https://github.com/tianiue/OpenWrt-Lan/releases/tag/2022.03.10-1957

**Comment by sbwml** [comment]
> 我不能启动，这是我打包的固件，你看看原因https://github.com/tianiue/OpenWrt-Lan/releases/tag/2022.03.10-1957

你这是固件 ，我怎么看，我也没法跑

你直接在终端丢 ```alist``` 就算失败起码也会有提示

**Comment by tianiue** [comment]
![12](https://user-images.githubusercontent.com/61725402/157796051-1e15125c-46d6-47a6-b1e5-57716927a6a9.png)
报错了一个

**Comment by sbwml** [comment]
> ![12](https://user-images.githubusercontent.com/61725402/157796051-1e15125c-46d6-47a6-b1e5-57716927a6a9.png) 报错了一个

缺失前端资源。https://github.com/sbwml/openwrt-alist/commit/8f4b584d694d8851ef1edb2b4b5b52966b32f363  这个提交之后被修复

**Comment by tianiue** [comment]
我是拉取你最新的库编译的，还是存在这个问题

**Comment by sbwml** [comment]
> 我是拉取你最新的库编译的，还是存在这个问题

如果直接在我仓库上拉取的最新源码，出现这种问题的可能性不高。当然你可以考虑两点原因，1、编译缓存  2、编译机网络（前端源码下载出错 & 编译出错任务不会被叫停）

**Comment by sbwml** [comment]
你也可以在此处下载prebuilt 安装包使用，它是基于OpenWRT SDK 编译，理论上支持大部分第三方维护的OP固件
https://github.com/sbwml/openwrt-alist/releases/tag/v2.1.3

**Comment by tianiue** [comment]
我是用github云编译的，编译了3次，结果都是一样

**Comment by sbwml** [comment]
这我就不清楚了

**Comment by tianiue** [comment]
![1113](https://user-images.githubusercontent.com/61725402/157997574-8bcad474-1cac-4c97-87ef-387862a53a37.png)
![11133](https://user-images.githubusercontent.com/61725402/157997593-588df5ea-4b2c-4a27-bf38-9bccac0d16f8.png)

昨天重新打包，还是一样，应该是哪里存在兼容问题

**Comment by tianiue** [comment]
2022-03-11T07:38:09.9429193Z WARNING: Makefile 'package/openwrt-packages/openwrt-alist/alist/Makefile' has a build dependency on 'golang/host', which does not exist
2022-03-11T07:38:09.9429978Z WARNING: Makefile 'package/openwrt-packages/openwrt-alist/alist/Makefile' has a build dependency on 'node/host', which does not exist
2022-03-11T07:38:09.9430966Z WARNING: Makefile 'package/openwrt-packages/openwrt-alist/alist/Makefile' has a build dependency on 'node-yarn/host', which does not exist
2022-03-11T07:38:09.9563920Z WARNING: Makefile 'package/openwrt-packages/openwrt-alist/luci-app-alist/Makefile' has a build dependency on 'luci-base/host', which does not exist

**Comment by sbwml** [comment]
> 

golang  和 nodejs 必须存在

https://github.com/openwrt/packages/tree/openwrt-21.02/lang/golang
https://github.com/openwrt/packages/tree/openwrt-21.02/lang/node
https://github.com/openwrt/packages/tree/openwrt-21.02/lang/node-yarn

按道理，这些东西默认存在于openwrt 默认feed上

**Comment by sbwml** [comment]
> ![1113](https://user-images.githubusercontent.com/61725402/157997574-8bcad474-1cac-4c97-87ef-387862a53a37.png) ![11133](https://user-images.githubusercontent.com/61725402/157997593-588df5ea-4b2c-4a27-bf38-9bccac0d16f8.png)
> 
> 昨天重新打包，还是一样，应该是哪里存在兼容问题

最后一个图片  data/config.json  配置，把assets 的内容修改成这样试试  ```"assets" : "/"```

**Comment by tianiue** [comment]
lean的源码是openwrt-18.06，存在不兼容吗？

**Comment by sbwml** [comment]
> lean的源码是openwrt-18.06，存在不兼容吗？

不知道 ，没接触过你说的这个lean

**Comment by tianiue** [comment]
> > lean的源码是openwrt-18.06，存在不兼容吗？
> 
> 不知道 ，没接触过你说的这个lean

https://github.com/coolsnowwolf/lede
https://github.com/coolsnowwolf/luci
https://github.com/coolsnowwolf/packages
这个仓库

**Comment by tianiue** [comment]
2.2.0还是一样打包了不能运行，安装正常

**Comment by sbwml** [comment]
> 2.2.0还是一样打包了不能运行，安装正常

也许是这插件本身做的就有问题   我服务器系统版本低   没法测试编译lean     所以帮不到你

不过在原版最新openwrt上编译和运行都是没有问题

**Comment by tianiue** [comment]
云编译脚本你可以测试一下 https://github.com/P3TERX/Actions-OpenWrt

**Comment by waynesg** [comment]
> lean的源码是openwrt-18.06，存在不兼容吗？

需要把node,golang,yarn编译进去。

**Comment by tianiue** [comment]
手动加上依赖可以啦

**Comment by XG-China** [comment]
请问下源码包含后台源码吗还有语言源码
官方源码刷了后没看到后台但是能正常运行

**Comment by sbwml** [comment]
> 请问下源码里包含后台源码和语言源码吗？
> 官方源码编译后没看到后台但是能正常运行！

alist 虽然是前后端源码分离的，但是在编译后，前端和后端会同时打包到二进制执行文件中，编译好后是无法看到前端的文件的

**Comment by sbwml** [comment]
> 手动加上依赖可以啦
> 打包成功增加了100M文件

正常情况下它不需要把node 和 golang 安装到固件中，openwrt 官方源码为例的话它只需要 node&yarn/host 、golang/host  ，makefile 也声明依赖了这点 https://github.com/sbwml/openwrt-alist/blob/master/alist/Makefile#L23

**Comment by XG-China** [comment]
好奇怪！我用官方的源码编译正常运行WEB页面不显示 用lede的源码编译WEB能显示不能运行！但是用lede编译的成品固件安装你提供的安装包可以成功运行

**Comment by sbwml** [comment]
我在虚拟机测试基于Lede 源码编译这个插件，确实存在问题，原因是lede 源码存在多个版本Nodejs  https://github.com/coolsnowwolf/packages/blob/master/lang/node/Makefile

而编译alist-web 前端需要 Nodejs 14 或以上版本，Lede 源码 node/host 默认情况下是使用  node 12版本就导致了这个 issues 所说的问题。

```
yarn install v1.22.17
warning package.json: No license field
warning alist-web@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error screenfull@6.0.1: The engine "node" is incompatible with this module. Expected version "^14.13.1 || >=16.0.0". Got "12.22.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
cp: cannot stat 'dist/*': No such file or directory
cp: target '../public/assets/' is not a directory
~/lede/package/alist/alist
Finding targets

Building targets
```

------------

这种问题我也不知道如何从本质上解决，但是如果条件允许的情况下，拉取feeds 源码后，将node源码更换为[OpenWRT](https://github.com/openwrt/packages/tree/master/lang/node) 官方的版本可以解决这个问题。

```
rm -rf feeds/packages/lang/node
svn co https://github.com/openwrt/packages/trunk/lang/node feeds/packages/lang/node
```
