### ISSUE TITLE
树莓派4B安装疑问？

### ISSUE THREAD

**Issue by GD2021** [sbwml/openwrt-alist#3]
![image](https://user-images.githubusercontent.com/81171294/161503966-98404158-e252-499b-9090-f11ec0fd2cfc.png)
请问我是树莓派4B上传安装了，这三个包，刷新后，为什么找到界面呢？

**Comment by sbwml** [comment]
> ![image](https://user-images.githubusercontent.com/81171294/161503966-98404158-e252-499b-9090-f11ec0fd2cfc.png) 请问我是树莓派4B上传安装了，这三个包，刷新后，为什么找到界面呢？

菜单位于：Luci界面 - 网络存储（NAS）项中
