### ISSUE TITLE
我使用的官方21.02，cpu是mt7621，安装mipsel_24kc版后启动不了

### ISSUE THREAD

**Issue by seaair-t** [sbwml/openwrt-alist#5]
![image](https://user-images.githubusercontent.com/97349076/164580044-66d3a459-0312-4672-8130-df902c073005.png)
是不是缺少依赖库？有哪些依赖库？

**Comment by seaair-t** [comment]
![image](https://user-images.githubusercontent.com/97349076/164581765-b51aff5b-24c8-4b89-a4b1-130dd15f9e4e.png)

**Comment by sbwml** [comment]
看起来像架构不对

在你路由器执行 ```opkg print-architecture``` 查看允许的包架构，最新 releases 已经添加了全部mips系列的架构，下载和你路由器对应的包应该就行

**Comment by seaair-t** [comment]
![image](https://user-images.githubusercontent.com/97349076/165896225-ff3dadc6-2478-47bf-bf7d-491f199912a5.png)
![image](https://user-images.githubusercontent.com/97349076/165896334-39e55965-be84-4127-8bbb-51e96727c116.png)
![image](https://user-images.githubusercontent.com/97349076/165896362-80ac5999-d9ca-4146-80c7-cb815d0dff81.png)
重新安装，结果还是一样

**Comment by sbwml** [comment]
> ![image](https://user-images.githubusercontent.com/97349076/165896225-ff3dadc6-2478-47bf-bf7d-491f199912a5.png) ![image](https://user-images.githubusercontent.com/97349076/165896334-39e55965-be84-4127-8bbb-51e96727c116.png) ![image](https://user-images.githubusercontent.com/97349076/165896362-80ac5999-d9ca-4146-80c7-cb815d0dff81.png) 重新安装，结果还是一样

你的固件在哪下载的   有没有sdk可以下载

**Comment by seaair-t** [comment]
![image](https://user-images.githubusercontent.com/97349076/165909689-11afa143-1357-4b2d-bb10-8057ef4cb96a.png)

用的是21.02官方稳定版固件https://openwrt.org/zh/start
