### ISSUE TITLE
配置资源找不到index.html

### ISSUE THREAD

**Issue by zhoujinshi** [sbwml/openwrt-alist#6]
openwrt alist_2.5.1-1_mipsel_24kc.ipk
配置了 "assets": "https://npm.elemecdn.com/alist-web@2.5.0/dist"
错误提示 open index.html: file does not exist

我直接使用alist-linux-musl-mipsle.tar.gz 这个是没问题的 可能使用openwrt 编译会压缩一些代码
使用这个可以运行 但是 解压后 33M 软路由空间不够用

[上级反馈过他说他不会OPENWRT编译](https://github.com/Xhofe/alist/discussions/1069)

**Comment by sbwml** [comment]
提供的 ipk 前端源码是现编译的，资源没有上传到任何cdn上（作为在openwrt上使用的版本，未来也不会考虑cdn方面。为确保可用性，也不会考虑使用alist-web 官方的成品前端资源进行构建，当然如果你是自己编译到openwrt固件的可以改变这个策略）。

你要用cdn 的话只能下载官方的二进制来使用

**Comment by zhoujinshi** [comment]
问题是只把luci-app-alist这个和主程序编译了，前端好像没有编译，全盘搜索index.html找不到，难道编写到主程序里面了，我直接下载前段dist也不知道解压到什么路径，配置文件就一个/。

**Comment by sbwml** [comment]
前端资源是被编译进alist 二进制程序中的。luci-app-alist 只是方便路由器Luci管理，即使没有它 alist 也可以正常工作。

而你要的cdn 这个仓库上的构建源码是没法满足你的。只能去alist 官方下载二进制来运行才可以使用cdn https://github.com/Xhofe/alist/releases

**Comment by zhoujinshi** [comment]
https://github.com/sbwml/openwrt-alist/releases/download/v2.5.1-2/alist_2.5.1-2_mipsel_24kc.ipk
我直接安装你的ipk文件好像里面不自带二进制模板  配置文件指定 / 的
